// Build data/national_points.js — a compact, homepage-friendly dataset of every
// A1 fatal-crash point (death within 24 h) across all 22 counties, 2016–2025.
//
// Quality gate: a point is kept only if it has real coordinates AND falls inside
// its own county's bounding box (computed from counties.geojson, +0.03° margin).
// This automatically drops mis-geocoded "displaced" points (e.g. [11,111] or a
// New Taipei crash that landed off the Taichung coast) without hand-editing.
//
// Row format (array-of-arrays to stay small):
//   [lat, lon, modeIdx, year, deaths, countyIdx, district]
// modeIdx → MODES;  countyIdx → COUNTIES.
const fs = require('fs');

const MODES = ['機車', '汽車', '人', '慢車', '其他'];
const MODES_EN = ['Motorcycle', 'Car / Truck', 'Pedestrian', 'Bicycle', 'Other'];
const norm = s => (s || '').replace(/臺/g, '台');

// Trim the redundant 縣市+區 prefix (county & district are stored separately)
// and collapse "A / A" duplicate halves → a compact, readable location.
function cleanLoc(loc) {
  const parts = (loc || '').split('/').map(s => {
    s = s.trim();
    let prev; do { prev = s; s = s.replace(/^.{2,3}[市縣].{1,4}[區鄉鎮市裡里]/, ''); } while (s !== prev);
    return s.trim();
  }).filter(Boolean);
  const seen = [];
  parts.forEach(p => { if (!seen.includes(p)) seen.push(p); });
  return seen.join(' / ') || (loc || '').trim();
}

// ── per-county bbox from counties.geojson ───────────────────────────
const geo = JSON.parse(fs.readFileSync('counties.geojson', 'utf8'));
const bbox = {};  // normalized COUNTYNAME -> [minLat,maxLat,minLon,maxLon]
function walk(coords, name) {
  if (typeof coords[0] === 'number') {
    const [lon, lat] = coords;
    const b = bbox[name];
    b[0] = Math.min(b[0], lat); b[1] = Math.max(b[1], lat);
    b[2] = Math.min(b[2], lon); b[3] = Math.max(b[3], lon);
  } else coords.forEach(c => walk(c, name));
}
geo.features.forEach(f => {
  const name = norm(f.properties.COUNTYNAME);
  bbox[name] = bbox[name] || [Infinity, -Infinity, Infinity, -Infinity];
  walk(f.geometry.coordinates, name);
});
const M = 0.03;  // degree margin (~3 km)

// ── county metadata (slug -> zh/en) from data/cities.js ─────────────
global.window = {};
require('./data/cities.js');
const CITIES = global.window.CITIES;
const COUNTIES = CITIES.map(c => ({ slug: c.slug, zh: c.zh, en: c.en }));
const countyIdx = {};
COUNTIES.forEach((c, i) => { countyIdx[c.slug] = i; });

// ── walk every county file, filter, collect ─────────────────────────
const pts = [];
const stats = { total: 0, kept: 0, noCoord: 0, displaced: 0 };
CITIES.forEach(c => {
  const file = `./data/${c.slug}.js`;
  global.window = {};
  delete require.cache[require.resolve(file)];
  require(file);
  const A = global.window.CITY_A1 || [];
  const b = bbox[norm(c.zh)];
  const ci = countyIdx[c.slug];
  A.forEach(r => {
    stats.total++;
    const lat = +r.lat, lon = +r.lon;
    if (!lat || !lon) { stats.noCoord++; return; }
    if (b && (lat < b[0] - M || lat > b[1] + M || lon < b[2] - M || lon > b[3] + M)) {
      stats.displaced++; return;
    }
    let mi = MODES.indexOf(r.mode); if (mi < 0) mi = 4;
    pts.push([
      +lat.toFixed(5), +lon.toFixed(5), mi, r.year,
      r.deaths || 1, ci, r.district || '',
      r.date || '', r.time || '', r.injuries || 0, cleanLoc(r.location)
    ]);
  });
  stats.kept += 0; // (kept counted below)
});
stats.kept = pts.length;

const out =
`// AUTO-GENERATED by build_national_points.js — do not edit by hand.
// Every A1 fatal-crash point (death within 24 h), all 22 counties, 2016–2025,
// filtered to its own county's bounding box (mis-geocoded points dropped).
// Row: [lat, lon, modeIdx, year, deaths, countyIdx, district, date, time, injuries, location]
window.NATIONAL_POINTS = {
  modes: ${JSON.stringify(MODES)},
  modes_en: ${JSON.stringify(MODES_EN)},
  counties: ${JSON.stringify(COUNTIES)},
  pts: [
${pts.map(p => '    ' + JSON.stringify(p)).join(',\n')}
  ]
};
`;
fs.writeFileSync('data/national_points.js', out);
console.log('stats:', JSON.stringify(stats));
console.log('output points:', pts.length, '· file KB:', (out.length / 1024).toFixed(0));
// quick mode histogram
const hist = {};
pts.forEach(p => { hist[MODES[p[2]]] = (hist[MODES[p[2]]] || 0) + 1; });
console.log('by mode:', JSON.stringify(hist));
